### ISSUE TITLE
C3po doesnt  keymap-local-set

### ISSUE THREAD

**Issue by polw1** [d1egoaz/c3po.el#5]
When writing c3po-dev or assistant options, the following error appears:

```save-current-buffer: Symbol’s function definition is void: keymap-local-set```

Any thoughts?

**Comment by d1egoaz** [comment]
What version of Emacs are you using?
Are you also using evil-mode?

**Comment by jkbjh** [comment]
I think I have the same problem (with Emacs 28, on debian stable bookworm ).
I'm not using evil-mode (is that required?).

Was `keymap-local-set` added in Emacs 29? I've tried adding a `(require 'compat)` to c3po.el (https://github.com/jkbjh/c3po.el/commit/9dac165fc31e4cebb2b6ecdbcf8e5689585da9de), which get's rid of that message.

I'm now stuck at:
```
Contacting host: api.openai.com:443
Wrong type argument: arrayp, nil
```
(in Messages)

(edit: this remaining problem likely was due to a rate limit / out of credit, so I guess there is an issue of parsing this error message. It works for me now.)
